---
- debug:
    msg: "{{ docker_compose_path }}"

- name: Create config directory.
  file:
    path: "{{ docker_compose_path }}"
    state: directory
    mode: "0755"

- name: Copy docker-compose to the remote node.
  copy:
    src: "docker-compose.yml"
    dest: "{{ docker_compose_path }}"
    mode: "0755"

- name: Install docker-compose
  pip:
    name: docker-compose
    state: absent

- name: Install docker
  pip:
    name: docker
    state: present
