---
- name: Create config directory.
  file:
    path: "{{ docker_config_path }}"
    state: directory
    mode: "0755"

- name: Copy docker-compose to the remote node.
  copy:
    src: "docker-compose.yml"
    dest: "{{ docker_compose_path }}"
    mode: "0755"

- name: Install docker Python package.
  pip:
    name: docker
    state: present
