# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.hostname = "openvpn"
  config.vm.box = "geerlingguy/centos8" 
  config.vm.network :private_network, ip: "192.168.56.43"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
